@echo off
echo Starting Backend...
start "Backend" cmd /k "cd /d %~dp0backend && python -m uvicorn app.main:app --reload"

echo Starting Frontend...
start "Frontend" cmd /k "cd /d %~dp0frontend && npm run dev"
